
function mostrarElemento() {
   var elemento = document.getElementById("mi-elemento");
   if (elemento.style.display === "none") {
     elemento.style.display = "block";
   } else {
     elemento.style.display = "none";
   }
 }
 function mostrarElemento1() {
   var elemento = document.getElementById("mi-elemento1");
   if (elemento.style.display === "none") {
     elemento.style.display = "block";
   } else {
     elemento.style.display = "none";
   }
 }
